Repository elwayman02/ember-data-github, pull requests merged in 2018-02, with the labels that each got.

#145 chore(package): update ember-data to version 3.0.1
  package.json
  tests/unit/serializers/github-release-test.js
  yarn.lock
Labels: internal

#146 generate changelog with lerna-changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: documentation

#147 Better organize supported apis
  README.md
Labels: documentation

#148 use embeddedrecord to pull user out of payloads
  addon/serializers/github-pull.js
  addon/serializers/github-release.js
  addon/serializers/github-repository.js
  tests/acceptance/github-release-test.js
  tests/acceptance/github-repository-test.js
  tests/acceptance/gitub-pull-test.js
Labels: enhancement

#140 Add github-compare
  README.md
  addon/adapters/github-compare.js
  addon/models/github-commit.js
  addon/models/github-compare.js
  addon/models/github-file.js
  addon/serializers/github-compare.js
  app/adapters/github-compare.js
  app/mirage-factories/github-commit.js
  app/mirage-factories/github-compare.js
  app/mirage-factories/github-file.js
  app/mirage-models/github-commit.js
  app/mirage-models/github-compare.js
  app/mirage-models/github-file.js
  app/models/github-commit.js
  app/models/github-compare.js
  app/models/github-file.js
  app/serializers/github-compare.js
  tests/acceptance/github-compare-test.js
  tests/dummy/mirage/config.js
  tests/dummy/mirage/factories/github-commit.js
  tests/dummy/mirage/factories/github-compare.js
  tests/dummy/mirage/factories/github-file.js
  tests/dummy/mirage/models/github-commit.js
  tests/dummy/mirage/models/github-compare.js
  tests/dummy/mirage/models/github-file.js
  tests/dummy/mirage/serializers/github-compare.js
  tests/helpers/custom-helpers/assert-github-compare-ok.js
  tests/helpers/start-app.js
  tests/unit/adapters/github-compare-test.js
  tests/unit/models/github-commit-test.js
  tests/unit/models/github-compare-test.js
  tests/unit/models/github-file-test.js
  tests/unit/serializers/github-compare-test.js
Labels: enhancement

#142 allow consuming apps to use mirage factories/models/serializers
  .eslintrc.js
  README.md
  index.js
  mirage-support/factories/github-blob.js
  mirage-support/factories/github-branch.js
  mirage-support/factories/github-commit.js
  mirage-support/factories/github-compare.js
  mirage-support/factories/github-file.js
  mirage-support/factories/github-organization.js
  mirage-support/factories/github-pull.js
  mirage-support/factories/github-release.js
  mirage-support/factories/github-repository.js
  mirage-support/factories/github-tree.js
  mirage-support/factories/github-user.js
  mirage-support/factories/tree.js
  mirage-support/models/github-branch.js
  mirage-support/models/github-commit.js
  mirage-support/models/github-compare.js
  mirage-support/models/github-file.js
  mirage-support/models/github-organization.js
  mirage-support/models/github-pull.js
  mirage-support/models/github-release.js
  mirage-support/models/github-repository.js
  mirage-support/models/github-user.js
  mirage-support/serializers/application.js
  mirage-support/serializers/github-compare.js
  mirage-support/serializers/github-pull.js
  mirage-support/serializers/github-release.js
  mirage-support/serializers/github-repository.js
  package.json
Labels: enhancement

#151 ember-cli-update to 3.0
  .eslintrc.js
  .travis.yml
  config/ember-try.js
  package.json
  testem.js
  tests/dummy/config/targets.js
  tests/helpers/.gitkeep
  yarn.lock
Labels: internal

#153 Retrieve Repo List By User
  README.md
  addon/adapters/github-repository.js
  addon/models/github-repository.js
  addon/models/github-user.js
  addon/serializers/github-repository.js
  tests/unit/adapters/github-repository-test.js
Labels: enhancement

#159 move github member mirage files for export
  mirage-support/factories/github-member.js
  mirage-support/models/github-member.js
Labels: enhancement
